import type { Metadata } from "next";

// GOOGLE FONTS
import { DM_Sans } from "next/font/google";

// GLOBALS CSS
import "@/styles/globals.css";

const dmSans = DM_Sans({
  variable : "--font-dm-sans",
  display : "swap",
  weight : ["400", "800"],
  subsets : ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
