import blog_img from "@/assets/images/blog-img.webp";
import blog_img1 from "@/assets/images/blog-img1.webp";
import blog_img2 from "@/assets/images/blog-img2.webp";
import blog_img3 from "@/assets/images/blog-img3.webp";
import blog_img4 from "@/assets/images/blog-img4.webp";
import blog_img5 from "@/assets/images/blog-img5.webp";
import blog_img6 from "@/assets/images/blog-img6.webp";
import blog_img7 from "@/assets/images/blog-img7.webp";
import blog_img8 from "@/assets/images/blog-img8.webp";
import blog_img9 from "@/assets/images/blog-img9.webp";
import blog_img10 from "@/assets/images/blog-img10.webp";
import blog_img11 from "@/assets/images/blog-img11.webp";


// MAIN DATA
export const SearchData = [
    {
        id: 0,
        img : blog_img,
        category : "Business",
        subCategory : "news",
        reading : "6",
        authorName : "ethan caldwell",
        month : "October",
        year : "2024",
        day : "16",
        title : "How Tech Shapes the Future of Work in 2024",
        description : "In today’s ever-evolving world, storytelling has become a powerful tool for connection. Revision provides a unique platform for individuals to",
    },
    {
        id: 1,
        img : blog_img1,
        category : "sport",
        subCategory : "travel",
        reading : "3",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "29",
        title : "The Future of Work: Tech and Remote Trends",
        description : "Find out why 2024 is predicted to be a pivotal year for sports technology and its impact on the industry.",
    },
    {
        id: 2,
        img : blog_img2,
        category : "news",
        subCategory : "trends",
        reading : "5",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "24",
        title : "Key Sports Trends for 2024: From AI to Virtual Reality",
        description : "Dive into the key sports trends like AI and virtual reality set to redefine the sports industry in 2024.",
    },
    {
        id: 3,
        img : blog_img3,
        category : "Business",
        reading : "7",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "20",
        title : "The Impact of Automation on Business Management Efficiency",
        description : "Learn how automation is boosting business management efficiency and driving growth in various sectors.",
    },
    {
        id: 4,
        img : blog_img4,
        category : "sport",
        reading : "4",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "15",
        title : "Startups Disrupting the Sports Industry with Innovative Tech",
        description : "Discover how startups are leveraging technology to disrupt and innovate within the sports industry.",
    },
    {
        id: 5,
        img : blog_img5,
        category : "technology",
        reading : "6",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "10",
        title : "Travel Trends in 2024: Virtual Tours and Immersive Experiences",
        description : "Explore the rise of virtual tours and immersive experiences shaping the future of travel in 2024.",
    },
    {
        id: 6,
        img : blog_img6,
        category : "sport",
        reading : "3",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "5",
        title : "Why Data Security is a Priority for Business Management in 2024",
        description : "Understand why data security is a growing concern for business management in today's digital world.",
    },
    {
        id: 7,
        img : blog_img7,
        category : "news",
        reading : "4",
        authorName : "ethan caldwell",
        month : "august",
        year : "2024",
        day : "30",
        title : "Startups and AI: How Artificial Intelligence Drives Innovative",
        description : "See how startups are harnessing the power of AI to foster innovation and reshape industries.",
    },
    {
        id: 8,
        img : blog_img8,
        category : "trends",
        reading : "6",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "27",
        title : "Remote Work Trends in Digital Age",
        description : "Discover the cutting-edge tech gadgets making travel smarter and more convenient in 2024.",
    },
    {
        id: 9,
        img : blog_img9,
        category : "startups",
        reading : "7",
        authorName : "ethan caldwell",
        month : "september",
        year : "2024",
        day : "25",
        title : "Business Travel Tools for the Digital Age",
        description : "Learn how startups are leveraging data to fuel growth and scale in today’s competitive landscape.",
    },
    {
        id: 10,
        img : blog_img10,
        category : "management",
        reading : "5",
        authorName : "ethan caldwell",
        month : "august",
        year : "2024",
        day : "25",
        title : "Top business Management Software Solutions for 2024",
        description : "Learn about the top management software solutions driving efficiency and growth in businesses.",
    },
    {
        id: 11,
        img : blog_img11,
        category : "technology",
        reading : "7",
        authorName : "ethan caldwell",
        month : "august",
        year : "2024",
        day : "20",
        title : "How 5G Technology Will Impact the Travel Industry in 2024",
        description : "Discover how 5G technology is set to revolutionize connectivity and enhance travel experiences.",
    },
];
