import { Metadata } from "next"
import React from "react"

export const metadata : Metadata = {
    title : "Create Next App",
    description : "Generated by created next app",
}

export default function AuthLayout({
    children
} : {
    children : React.ReactNode
}){
    return <>
        <main>
            {children}
        </main>
    </>
}