import { Metadata } from "next";
import React from "react";

export const metadata : Metadata = {
    title : "Create Next App",
    description : "Generated by created next app",
}

export default function AdminLayout({
    children
} : {
    children : React.ReactNode
}) {
    return <>
    <div>
        {children}
    </div>
    </>
}